### ISSUE TITLE
Can't compile with 6.5

### ISSUE THREAD

**Issue by akiradeveloper** [akiradeveloper/userland-io#37]
```
With 6.5 kernel, abuse-mod can't be compiled. Let's fix it

```
DKMS make.log for abuse-1.0.0 for kernel 6.5.0-1018-azure (x86_64)
Wed May  8 0[7](https://github.com/akiradeveloper/userland-io/actions/runs/8997700676/job/24716360320#step:7:8):05:07 UTC 2024
make[1]: Entering directory '/var/lib/dkms/abuse/1.0.0/build'
make -C /lib/modules/6.5.0-101[8](https://github.com/akiradeveloper/userland-io/actions/runs/8997700676/job/24716360320#step:7:9)-azure/build M=/var/lib/dkms/abuse/1.0.0/build modules
make[2]: Entering directory '/usr/src/linux-headers-6.5.0-1018-azure'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-11 (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
  You are using:           gcc-11 (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
  CC [M]  /var/lib/dkms/abuse/1.0.0/build/abuse.o
In file included from /var/lib/dkms/abuse/1.0.0/build/abuse.c:2[9](https://github.com/akiradeveloper/userland-io/actions/runs/8997700676/job/24716360320#step:7:10):
/var/lib/dkms/abuse/1.0.0/build/abuse.h:116:41: error: ‘BIO_MAX_PAGES’ undeclared here (not in a function); did you mean ‘BIO_MAX_VECS’?
  116 |         struct abuse_vec        ab_xfer[BIO_MAX_PAGES];
      |                                         ^~~~~~~~~~~~~
      |                                         BIO_MAX_VECS
/var/lib/dkms/abuse/1.0.0/build/abuse.c: In function ‘reread_partition’:
/var/lib/dkms/abuse/1.0.0/build/abuse.c:92:9: error: unknown type name ‘mm_segment_t’
   92 |         mm_segment_t old_fs = get_fs();
      |         ^~~~~~~~~~~~
/var/lib/dkms/abuse/1.0.0/build/abuse.c:92:31: error: implicit declaration of function ‘get_fs’; did you mean ‘get_bh’? [-Werror=implicit-function-declaration]
   92 |         mm_segment_t old_fs = get_fs();
      |                               ^~~~~~
      |                               get_bh
/var/lib/dkms/abuse/1.0.0/build/abuse.c:93:9: error: implicit declaration of function ‘set_fs’; did you mean ‘sget_fc’? [-Werror=implicit-function-declaration]
   93 |         set_fs(KERNEL_DS);
      |         ^~~~~~
      |         sget_fc
/var/lib/dkms/abuse/1.0.0/build/abuse.c:93:16: error: ‘KERNEL_DS’ undeclared (first use in this function); did you mean ‘KERNFS_NS’?
   93 |         set_fs(KERNEL_DS);
      |                ^~~~~~~~~
      |                KERNFS_NS
/var/lib/dkms/abuse/1.0.0/build/abuse.c:93:16: note: each undeclared identifier is reported only once for each function it appears in
/var/lib/dkms/abuse/1.0.0/build/abuse.c:94:15: error: implicit declaration of function ‘blkdev_ioctl’; did you mean ‘blkdev_put’? [-Werror=implicit-function-declaration]
   94 |         res = blkdev_ioctl(bdev, 0, BLKRRPART, 0);
      |               ^~~~~~~~~~~~
      |               blkdev_put
/var/lib/dkms/abuse/1.0.0/build/abuse.c: In function ‘abuse_reset’:
/var/lib/dkms/abuse/1.0.0/build/abuse.c:117:17: error: implicit declaration of function ‘bd_set_size’ [-Werror=implicit-function-declaration]
  117 |                 bd_set_size(ab->ab_device, 0);
      |                 ^~~~~~~~~~~
In file included from /var/lib/dkms/abuse/1.0.0/build/abuse.c:18:
./include/linux/fs.h:111:33: warning: passing argument 2 of ‘blkdev_put’ makes pointer from integer without a cast [-Wint-conversion]
  111 | #define FMODE_READ              ((__force fmode_t)0x1)
      |                                 ^~~~~~~~~~~~~~~~~~~~~~
      |                                 |
      |                                 unsigned int
/var/lib/dkms/abuse/1.0.0/build/abuse.c:122:43: note: in expansion of macro ‘FMODE_READ’
  122 |                 blkdev_put(ab->ab_device, FMODE_READ);
      |                                           ^~~~~~~~~~
In file included from /var/lib/dkms/abuse/1.0.0/build/abuse.c:23:
./include/linux/blkdev.h:1481:50: note: expected ‘void *’ but argument is of type ‘unsigned int’
 1481 | void blkdev_put(struct block_device *bdev, void *holder);
      |                                            ~~~~~~^~~~~~
/var/lib/dkms/abuse/1.0.0/build/abuse.c: In function ‘abuse_set_status_int’:
/var/lib/dkms/abuse/1.0.0/build/abuse.c:164:24: error: implicit declaration of function ‘bdget_disk’; did you mean ‘put_disk’? [-Werror=implicit-function-declaration]
  164 |                 bdev = bdget_disk(ab->ab_disk, 0);
      |                        ^~~~~~~~~~
      |                        put_disk
/var/lib/dkms/abuse/1.0.0/build/abuse.c:164:22: warning: assignment to ‘struct block_device *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  164 |                 bdev = bdget_disk(ab->ab_disk, 0);
      |                      ^
/var/lib/dkms/abuse/1.0.0/build/abuse.c:169:23: error: implicit declaration of function ‘blkdev_get’; did you mean ‘blkdev_put’? [-Werror=implicit-function-declaration]
  169 |                 err = blkdev_get(bdev, FMODE_READ, NULL);
      |                       ^~~~~~~~~~
      |                       blkdev_put
/var/lib/dkms/abuse/1.0.0/build/abuse.c:171:25: error: implicit declaration of function ‘bdput’; did you mean ‘fdput’? [-Werror=implicit-function-declaration]
  171 |                         bdput(bdev);
      |                         ^~~~~
      |                         fdput
/var/lib/dkms/abuse/1.0.0/build/abuse.c:187:9: error: implicit declaration of function ‘set_device_ro’; did you mean ‘set_disk_ro’? [-Werror=implicit-function-declaration]
  187 |         set_device_ro(bdev, (ab->ab_flags & ABUSE_FLAGS_READ_ONLY) != 0);
      |         ^~~~~~~~~~~~~
      |         set_disk_ro
/var/lib/dkms/abuse/1.0.0/build/abuse.c: In function ‘xfr_command_from_cmd_flags’:
/var/lib/dkms/abuse/1.0.0/build/abuse.c:255:22: error: ‘REQ_OP_WRITE_SAME’ undeclared (first use in this function); did you mean ‘CMD_OP_WRITE_SAME’?
  255 |                 case REQ_OP_WRITE_SAME:
      |                      ^~~~~~~~~~~~~~~~~
      |                      CMD_OP_WRITE_SAME
/var/lib/dkms/abuse/1.0.0/build/abuse.c: At top level:
/var/lib/dkms/abuse/1.0.0/build/abuse.c:539:17: error: initialization of ‘int (*)(struct gendisk *, blk_mode_t)’ {aka ‘int (*)(struct gendisk *, unsigned int)’} from incompatible pointer type ‘int (*)(struct block_device *, fmode_t)’ {aka ‘int (*)(struct block_device *, unsigned int)’} [-Werror=incompatible-pointer-types]
  539 |         .open = ab_open,
      |                 ^~~~~~~
/var/lib/dkms/abuse/1.0.0/build/abuse.c:539:17: note: (near initialization for ‘ab_fops.open’)
/var/lib/dkms/abuse/1.0.0/build/abuse.c:540:25: error: initialization of ‘void (*)(struct gendisk *)’ from incompatible pointer type ‘void (*)(struct gendisk *, fmode_t)’ {aka ‘void (*)(struct gendisk *, unsigned int)’} [-Werror=incompatible-pointer-types]
  540 |         .release =      ab_release,
      |                         ^~~~~~~~~~
/var/lib/dkms/abuse/1.0.0/build/abuse.c:540:25: note: (near initialization for ‘ab_fops.release’)
/var/lib/dkms/abuse/1.0.0/build/abuse.c: In function ‘abuse_alloc’:
/var/lib/dkms/abuse/1.0.0/build/abuse.c:641:30: error: implicit declaration of function ‘alloc_disk’; did you mean ‘alloc_uid’? [-Werror=implicit-function-declaration]
  641 |         disk = ab->ab_disk = alloc_disk(num_minors);
      |                              ^~~~~~~~~~
      |                              alloc_uid
/var/lib/dkms/abuse/1.0.0/build/abuse.c:641:28: warning: assignment to ‘struct gendisk *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  641 |         disk = ab->ab_disk = alloc_disk(num_minors);
      |                            ^
/var/lib/dkms/abuse/1.0.0/build/abuse.c:660:9: error: implicit declaration of function ‘blk_cleanup_queue’ [-Werror=implicit-function-declaration]
  660 |         blk_cleanup_queue(ab->ab_queue);
      |         ^~~~~~~~~~~~~~~~~
/var/lib/dkms/abuse/1.0.0/build/abuse.c: In function ‘abuse_probe’:
/var/lib/dkms/abuse/1.0.0/build/abuse.c:34:28: error: implicit declaration of function ‘get_disk_and_module’ [-Werror=implicit-function-declaration]
   34 | #define compat_get_disk(x) get_disk_and_module((x))
      |                            ^~~~~~~~~~~~~~~~~~~
/var/lib/dkms/abuse/1.0.0/build/abuse.c:693:21: note: in expansion of macro ‘compat_get_disk’
  693 |         kobj = ab ? compat_get_disk(ab->ab_disk) : ERR_PTR(-ENOMEM);
      |                     ^~~~~~~~~~~~~~~
/var/lib/dkms/abuse/1.0.0/build/abuse.c:693:50: warning: pointer/integer type mismatch in conditional expression
  693 |         kobj = ab ? compat_get_disk(ab->ab_disk) : ERR_PTR(-ENOMEM);
      |                                                  ^
In file included from ./include/linux/linkage.h:7,
                 from ./arch/x86/include/asm/cache.h:5,
                 from ./include/linux/cache.h:6,
                 from ./include/linux/time.h:5,
                 from ./include/linux/stat.h:19,
                 from ./include/linux/module.h:13,
                 from /var/lib/dkms/abuse/1.0.0/build/abuse.c:15:
/var/lib/dkms/abuse/1.0.0/build/abuse.c: In function ‘abuse_init’:
./include/linux/export.h:29:22: error: passing argument 1 of ‘class_create’ from incompatible pointer type [-Werror=incompatible-pointer-types]
   29 | #define THIS_MODULE (&__this_module)
      |                     ~^~~~~~~~~~~~~~~
      |                      |
      |                      struct module *
/var/lib/dkms/abuse/1.0.0/build/abuse.c:772:36: note: in expansion of macro ‘THIS_MODULE’
  772 |         abuse_class = class_create(THIS_MODULE, "abuse");
      |                                    ^~~~~~~~~~~
In file included from ./include/linux/device.h:31,
                 from ./include/linux/blk_types.h:11,
                 from ./include/linux/blkdev.h:9,
                 from /var/lib/dkms/abuse/1.0.0/build/abuse.c:23:
./include/linux/device/class.h:230:54: note: expected ‘const char *’ but argument is of type ‘struct module *’
  230 | struct class * __must_check class_create(const char *name);
      |                                          ~~~~~~~~~~~~^~~~
/var/lib/dkms/abuse/1.0.0/build/abuse.c:772:23: error: too many arguments to function ‘class_create’
  772 |         abuse_class = class_create(THIS_MODULE, "abuse");
      |                       ^~~~~~~~~~~~
In file included from ./include/linux/device.h:31,
                 from ./include/linux/blk_types.h:11,
                 from ./include/linux/blkdev.h:9,
                 from /var/lib/dkms/abuse/1.0.0/build/abuse.c:23:
./include/linux/device/class.h:230:29: note: declared here
  230 | struct class * __must_check class_create(const char *name);
      |                             ^~~~~~~~~~~~
/var/lib/dkms/abuse/1.0.0/build/abuse.c:788:9: error: implicit declaration of function ‘blk_register_region’; did you mean ‘blk_register_queue’? [-Werror=implicit-function-declaration]
  788 |         blk_register_region(MKDEV(ABUSE_MAJOR, 0), range, THIS_MODULE, abuse_probe, NULL, NULL);
      |         ^~~~~~~~~~~~~~~~~~~
      |         blk_register_queue
/var/lib/dkms/abuse/1.0.0/build/abuse.c: In function ‘abuse_exit’:
/var/lib/dkms/abuse/1.0.0/build/abuse.c:816:9: error: implicit declaration of function ‘blk_unregister_region’; did you mean ‘blk_unregister_queue’? [-Werror=implicit-function-declaration]
  816 |         blk_unregister_region(MKDEV(ABUSE_MAJOR, 0), range);
      |         ^~~~~~~~~~~~~~~~~~~~~
      |         blk_unregister_queue
/var/lib/dkms/abuse/1.0.0/build/abuse.c: In function ‘abuse_init’:
/var/lib/dkms/abuse/1.0.0/build/abuse.c:785:17: warning: ignoring return value of ‘add_disk’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  785 |                 add_disk(ab->ab_disk);
      |                 ^~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/abuse/1.0.0/build/abuse.c: In function ‘abuse_add_one’:
/var/lib/dkms/abuse/1.0.0/build/abuse.c:681:17: warning: ignoring return value of ‘add_disk’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  681 |                 add_disk(ab->ab_disk);
      |                 ^~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/abuse/1.0.0/build/abuse.c: In function ‘abctl_ioctl’:
/var/lib/dkms/abuse/1.0.0/build/abuse.c:451:25: warning: ignoring return value of ‘add_disk’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  451 |                         add_disk(new->ab_disk);
      |                         ^~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[4]: *** [scripts/Makefile.build:251: /var/lib/dkms/abuse/1.0.0/build/abuse.o] Error 1
make[3]: *** [/usr/src/linux-headers-6.5.0-[10](https://github.com/akiradeveloper/userland-io/actions/runs/8997700676/job/24716360320#step:7:11)18-azure/Makefile:2039: /var/lib/dkms/abuse/1.0.0/build] Error 2
make[2]: *** [Makefile:234: __sub-make] Error 2
make[2]: Leaving directory '/usr/src/linux-headers-6.5.0-1018-azure'
make[1]: *** [Makefile:7: all] Error 2
make[1]: Leaving directory '/var/lib/dkms/abuse/1.0.0/build'
```

**Comment by akiradeveloper** [comment]
BIO_MAX_PAGES is just renamed. 

```
/var/lib/dkms/abuse/1.0.0/build/abuse.h:116:41: error: ‘BIO_MAX_PAGES’ undeclared here (not in a function); did you mean ‘BIO_MAX_VECS’?
  116 |         struct abuse_vec        ab_xfer[BIO_MAX_PAGES];
      |                                         ^~~~~~~~~~~~~
      |                                         BIO_MAX_VECS
```


https://github.com/torvalds/linux/commit/a8affc03a9b375e19bc81573de0c9108317d78c7

**Comment by akiradeveloper** [comment]
Can we remove anything other than blkdev_ctl line? This PR looks fixing that way https://github.com/aircrack-ng/rtl8812au/commit/4573749621508b6799b84e92d6b08505fc5a2a7e

```c
static int reread_partition(struct block_device *bdev) {
	#if LINUX_VERSION_CODE >= KERNEL_VERSION(5,8,0)
	int res;
	mm_segment_t old_fs = get_fs();
	set_fs(KERNEL_DS);
	res = blkdev_ioctl(bdev, 0, BLKRRPART, 0);
	set_fs(old_fs);
```

**Comment by akiradeveloper** [comment]
```
/var/lib/dkms/abuse/1.0.0/build/abuse.c: In function ‘abuse_reset’:
/var/lib/dkms/abuse/1.0.0/build/abuse.c:117:17: error: implicit declaration of function ‘bd_set_size’ [-Werror=implicit-function-declaration]
117 | bd_set_size(ab->ab_device, 0);
| ^~~~~~~~~~~
```

https://listman.redhat.com/archives/dm-devel/2020-August/042576.html

**Comment by akiradeveloper** [comment]
```
/var/lib/dkms/abuse/1.0.0/build/abuse.c:185:9: error: implicit declaration of function ‘set_device_ro’; did you mean ‘set_disk_ro’? [-Werror=implicit-function-declaration]
  185 |         set_device_ro(bdev, (ab->ab_flags & ABUSE_FLAGS_READ_ONLY) != 0);
      |         ^~~~~~~~~~~~~
      |         set_disk_ro
```

[09/10] block: remove set_device_ro

https://patchwork.kernel.org/project/linux-block/patch/20201103100018.683694-10-hch@lst.de/

**Comment by akiradeveloper** [comment]
```
/var/lib/dkms/abuse/1.0.0/build/abuse.c: In function ‘xfr_command_from_cmd_flags’:
/var/lib/dkms/abuse/1.0.0/build/abuse.c:253:22: error: ‘REQ_OP_WRITE_SAME’ undeclared (first use in this function); did you mean ‘CMD_OP_WRITE_SAME’?
  253 |                 case REQ_OP_WRITE_SAME:
      |                      ^~~~~~~~~~~~~~~~~
      |                      CMD_OP_WRITE_SAME
```

What? write-same is removed? Amazing. For what reason?

https://patchwork.kernel.org/project/linux-scsi/patch/20170410160807.23674-7-hch@lst.de/

**Comment by akiradeveloper** [comment]
I think `device_create` is missing but `device_destory` is called. very weird.
The code is to automatically create devices on kernel load and I think it is removed.

**Comment by akiradeveloper** [comment]
```
/var/lib/dkms/abuse/1.0.0/build/abuse.c:639:28: warning: assignment to ‘struct gendisk *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  639 |         disk = ab->ab_disk = alloc_disk(num_minors);
```

Maybe, we can use instead (from loop.c)

```c
disk = lo->lo_disk = blk_mq_alloc_disk(&lo->tag_set, lo);
```

**Comment by akiradeveloper** [comment]
```
/var/lib/dkms/abuse/1.0.0/build/abuse.c:786:9: error: implicit declaration of function ‘blk_register_region’; did you mean ‘blk_register_queue’? [-Werror=implicit-function-declaration]
  786 |         blk_register_region(MKDEV(ABUSE_MAJOR, 0), range, THIS_MODULE, abuse_probe, NULL, NULL);
      |         ^~~~~~~~~~~~~~~~~~~
      |         blk_register_queue
```

```
/var/lib/dkms/abuse/1.0.0/build/abuse.c:34:28: error: implicit declaration of function ‘get_disk_and_module’ [-Werror=implicit-function-declaration]
   34 | #define compat_get_disk(x) get_disk_and_module((x))
      |                            ^~~~~~~~~~~~~~~~~~~
```

is related to

https://lists.linbit.com/pipermail/drbd-dev/2020-November/005400.html

**Comment by akiradeveloper** [comment]
```
/var/lib/dkms/abuse/1.0.0/build/abuse.c:167:23: error: implicit declaration of function ‘blkdev_get’; did you mean ‘blkdev_put’? [-Werror=implicit-function-declaration]
  167 |                 err = blkdev_get(bdev, FMODE_READ, NULL);
      |                       ^~~~~~~~~~
      |                       blkdev_put
```

is because the API was deleted.

https://lore.kernel.org/lkml/20200917165720.3285256-9-hch@lst.de/T/


```c
-	err = blkdev_get(bdev, FMODE_READ, NULL);
-	if (err < 0)
-		goto exit;
-	blkdev_put(bdev, FMODE_READ);
+	bdev = blkdev_get_by_dev(disk_devt(disk), FMODE_READ, NULL);
+	if (!IS_ERR(bdev))
+		blkdev_put(bdev, FMODE_READ);
```

**Comment by akiradeveloper** [comment]
Instead of `invalidate_bdev`, better to use

```c
/**
 * invalidate_disk - invalidate the disk
 * @disk: the struct gendisk to invalidate
 *
 * A helper to invalidates the disk. It will clean the disk's associated
 * buffer/page caches and reset its internal states so that the disk
 * can be reused by the drivers.
 *
 * Context: can sleep
 */
void invalidate_disk(struct gendisk *disk)
{
	struct block_device *bdev = disk->part0;

	invalidate_bdev(bdev);
	bdev->bd_inode->i_mapping->wb_err = 0;
	set_capacity(disk, 0);
}
EXPORT_SYMBOL(invalidate_disk);
```

**Comment by akiradeveloper** [comment]
Maybe we can use /dev/mem to map the pages to virtual memory.

https://elixir.bootlin.com/linux/latest/source/drivers/char/mem.c#L343

**Comment by akiradeveloper** [comment]
done.
